-- MySQL Script generated by MySQL Workbench
-- Sat Jun 26 15:41:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HotelBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HotelBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HotelBD` DEFAULT CHARACTER SET utf8 ;
USE `HotelBD` ;

-- -----------------------------------------------------
-- Table `HotelBD`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBD`.`Usuario` (
  `Cod_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nome_Usuario` VARCHAR(50) NOT NULL,
  `Senha_Usuario` VARCHAR(10) NOT NULL,
  `Nivel_Acesso` ENUM('1', '2', '3') NOT NULL,
  `Data_Nascimento` DATE NOT NULL,
  `Data_Inclusao` DATETIME NOT NULL,
  `Sexo` ENUM('1', '2', '3') NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `RG` VARCHAR(20) NOT NULL,
  `Endereco` VARCHAR(100) NOT NULL,
  `Numero` VARCHAR(10) NOT NULL,
  `Complemento` VARCHAR(45) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`Cod_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelBD`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBD`.`Funcionario` (
  `Codigo_Matricula` INT NOT NULL AUTO_INCREMENT,
  `FK_Codigo_Usuario` INT NOT NULL,
  `Data_Admissao` DATE NOT NULL,
  `Escolaridade` ENUM('1', '2', '3') NOT NULL,
  `Cargo` ENUM('1', '2') NOT NULL,
  `Situacao` ENUM('1', '2', '3') NOT NULL,
  INDEX `FK_Codigo_Usuario` (`FK_Codigo_Usuario` ASC) INVISIBLE,
  PRIMARY KEY (`Codigo_Matricula`),
  CONSTRAINT `fk_table1_Usuario`
    FOREIGN KEY (`FK_Codigo_Usuario`)
    REFERENCES `HotelBD`.`Usuario` (`Cod_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelBD`.`Hospede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBD`.`Hospede` (
  `Cod_Hospede` INT NOT NULL AUTO_INCREMENT,
  `FK_Codigo_Usuario` INT NOT NULL,
  `FK_Responsavel` INT NULL,
  INDEX `FK_Codigo_Usuario` (`FK_Codigo_Usuario` ASC) VISIBLE,
  PRIMARY KEY (`Cod_Hospede`),
  CONSTRAINT `FK_Codigo_Usuario`
    FOREIGN KEY (`FK_Codigo_Usuario`)
    REFERENCES `HotelBD`.`Usuario` (`Cod_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelBD`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBD`.`Hotel` (
  `Codigo_Hotel` INT NOT NULL AUTO_INCREMENT,
  `FK_Gerente` INT NOT NULL,
  `Nome_Hotel` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(18) NOT NULL,
  `IE` VARCHAR(20) NOT NULL,
  `Endereco` VARCHAR(100) NOT NULL,
  `Numero` VARCHAR(10) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `Telefone` VARCHAR(18) NOT NULL,
  INDEX `FK_Gerente` (`FK_Gerente` ASC) VISIBLE,
  PRIMARY KEY (`Codigo_Hotel`),
  CONSTRAINT `FK_Gerente`
    FOREIGN KEY (`FK_Gerente`)
    REFERENCES `HotelBD`.`Funcionario` (`Codigo_Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelBD`.`Apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBD`.`Apartamento` (
  `ID_Apto` INT NOT NULL AUTO_INCREMENT,
  `FK_Codigo_Hotel` INT NOT NULL,
  `Numero_Apartemanto` VARCHAR(10) NOT NULL,
  `Numero_Chave` VARCHAR(45) NOT NULL,
  `Tipo_Apartamento` ENUM('1', '2', '3') NOT NULL,
  `Tipo_Acomodacao` ENUM('1', '2', '3') NOT NULL,
  `QTD_Cama` INT NOT NULL,
  `TV` TINYINT NULL,
  `Frigobar` TINYINT NULL,
  `Banheira` TINYINT NULL,
  `Situacao` TINYINT NULL,
  `Valor_Diaria` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`ID_Apto`),
  INDEX `FK_Codigo_Hotel` (`FK_Codigo_Hotel` ASC) VISIBLE,
  CONSTRAINT `FK_Codigo_Hotel`
    FOREIGN KEY (`FK_Codigo_Hotel`)
    REFERENCES `HotelBD`.`Hotel` (`Codigo_Hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelBD`.`Hospedagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBD`.`Hospedagem` (
  `ID_Registro` INT NOT NULL AUTO_INCREMENT,
  `FK_Codigo_Apto` INT NOT NULL,
  `FK_Codigo_Hospede` INT NOT NULL,
  `Check_IN` DATETIME NOT NULL,
  `Check_Out` DATETIME NOT NULL,
  INDEX `FK_Codigo_Apto` (`FK_Codigo_Apto` ASC) VISIBLE,
  INDEX `FK_Codigo_Hospede` (`FK_Codigo_Hospede` ASC) VISIBLE,
  PRIMARY KEY (`ID_Registro`),
  CONSTRAINT `FK_Codigo_Apto`
    FOREIGN KEY (`FK_Codigo_Apto`)
    REFERENCES `HotelBD`.`Apartamento` (`ID_Apto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Codigo_Hospede`
    FOREIGN KEY (`FK_Codigo_Hospede`)
    REFERENCES `HotelBD`.`Hospede` (`Cod_Hospede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
